# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  seed: 1337
  tensorboard_logdir: tblog

checkpoint:
  save_interval_updates: 5000
  keep_interval_updates: 1
  no_epoch_checkpoints: true


distributed_training:
  ddp_backend: no_c10d
  distributed_backend: 'nccl'
  distributed_world_size: 32
  distributed_port: 29671
  nprocs_per_node: 8
  find_unused_parameters: true

task:
  _name: hubert_info_align_pretraining
  data: ???
  label_dir: ???
  labels: ???
  label_rate: ${model.label_rate}
  sample_rate: 16000
  max_sample_size: 250000
  min_sample_size: 32000
  pad_audio: false
  random_crop: true
  normalize: false # must be consistent with extractor

dataset:
  num_workers: 6
  max_tokens: 1400000
  skip_invalid_size_inputs_valid_test: true
  validate_interval: 5
  validate_interval_updates: 5000

criterion:
  _name: hubert_info_align
  pred_masked_weight: 1.0

optimization:
  max_update: 100000
  lr: [0.0005]
  clip_norm: 10.0

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 8000

model:
  _name: hubert_info_align
  pretrained_hubert_ckpt: ???
  label_rate: ???
  mask_random: True 
  hide_random: True 
  mask_lengths: [5, 50]
  hide_lengths: [5, 50]
  num_mask_spans: [1]
  num_hide_spans: [1]
  mask_selection: 'static'
  no_mask_overlap: True 
  mask_min_space: 1
  mask_channel_prob: 0.0
  extractor_mode: default
  conv_feature_layers: '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2'
  final_dim: 256
  decoder_encoder_embed_dim: 256
  decoder_embed_dim: 256
  decoder_ffn_embed_dim: 2048 
  decoder_layers: 6
  decoder_attention_heads: 8 
  decoder_normalize_before: True 
  decoder_learned_pos: False
  share_decoder_input_output_embed: True 
  no_token_positional_embeddings: False 
  decoder_layerdrop: 0.0
  decoder_output_dim: 256
  decoder_input_dim: 256
  decoder_dropout: 0.1
  decoder_activation_dropout: 0.1
  relu_dropout: 0.1
  adaptive_softmax_dropout: 0.0
  n_frames_per_step: 1


hydra:
  job:
    config:
      override_dirname:
        kv_sep: '-'
        item_sep: '__'
        exclude_keys:
          - run
          - task.data
          - task.label_dir
  run:
    dir: ???
  sweep:
    dir: ???
    subdir: ${hydra.job.config_name}__${hydra.job.override_dirname}
